sudo: false
language: c
os:
    - linux
env:
    - PATH=$PWD/Nim/bin:$PATH
install: .travis/install.sh
before_script:
    - set -e
    - set -x
script:
    - cd test
    - nim c -d:ssl -d:testing -r toauth1.nim
    - nim c -d:ssl -d:testing -r toauth2.nim
    - cd ..
