name: Build

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [ 'stable', 'devel' ]
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: nimble install -y
      - run: nimble test
